### ISSUE TITLE
Distributed processing

### ISSUE THREAD

**Issue by pzelasko** [pzelasko/lhotse#11]
Some time ago I was looking for alternatives to `run.pl`/`queue.pl` style of distributing work on a cluster, hoping for something that would both interface nicely with SGE and allow to stay 100% in Python at the same time. I discovered that [dask is able to do that](https://jobqueue.dask.org/en/latest/index.html), and I was able to run some simple computations on CLSP cluster this way. I know it also supports slurm and some other grid engines, we could have a "local" backend too. 

The minimal code to achieve that looks more or less like that:

```
from dask_jobqueue import SGECluster
from dask.distributed import Client

def run_jobs(
        fn,
        inputs,
        jobs=1,
        memory='1GB',
        timeout_s='600',
        queue='all.q',
        proc_per_worker=1,
        cores_per_proc=1,
        env_extra=None,
        **kwargs
):
    if env_extra is None:
        env_extra = []
    with SGECluster(
            queue=queue,
            walltime=timeout_s,
            processes=proc_per_worker,
            memory=memory,
            cores=cores_per_proc,
            env_extra=env_extra  # e.g. ['export ENV_VARIABLE="SOMETHING"', 'source myscript.sh']
    ) as cluster:
        with Client(cluster) as client:
            cluster.scale(jobs)
            futures = client.map(fn, inputs)
            results = client.gather(futures)
    return results
```

and can be used like:

```
def process_item(x):
    pass  # do processing

items = [ ... ]

results = run_jobs(process_item, items)
``` 

I'd like to know if you'd be interested in giving it a try and exploring this option. @danpovey @jtrmal

**Comment by danpovey** [comment]
Hm, that's interesting.  Where do the logs go?

How about the case where we want the individual nodes to write the file output directly?

How about the case when you want to parallelize on the local machine?

Regardless, I don't want to integrate this too tightly with the other pieces; I'd like a separation of concerns as much as possible.  Maybe we could have the notion of splitting a manifest file to job n of k.

**Comment by danpovey** [comment]
Hm, that's interesting.  Where do the logs go?

How about the case where we want the individual nodes to write the file output directly?

How about the case when you want to parallelize on the local machine?

Regardless, I don't want to integrate this too tightly with the other pieces; I'd like a separation of concerns as much as possible.  Maybe we could have the notion of splitting a manifest file to job n of k.

**Comment by pzelasko** [comment]
> Hm, that's interesting. Where do the logs go?

I think I saw it create some queue-related logs somewhere in the home directory, maybe it's a configurable thing. Regarding task-related logs, that remains to be explored - I didn't try to interact with the `logging` module yet.

> How about the case where we want the individual nodes to write the file output directly?

You would likely pass the output filename as one of the arguments.

> How about the case when you want to parallelize on the local machine?

Create a different "backend" for this function which uses `concurrent.futures.ProcessPoolExecutor` (you'd need multiple backends anyway to support SGE, Slurm, etc.). 

> Regardless, I don't want to integrate this too tightly with the other pieces; I'd like a separation of concerns as much as possible. Maybe we could have the notion of splitting a manifest file to job n of k.

👍

**Comment by pzelasko** [comment]
This one is out of scope - maybe one day I'll explore it and make a separate repo ;)
