### ISSUE TITLE
Couple comments on reading

### ISSUE THREAD

**Issue by danpovey** [pzelasko/lhotse#2]
https://github.com/pzelasko/lhotse/blob/7555df605def57836c9454ae44aac95c504d86b0/lhotse/audio.py#L21

There should possibly be at least a TODO here to support getting a subset of channels.  I'm thinking of scenarios like Switchboard.  Since I think typical storage formats store the different channels interleaved, it may be just as efficient to read all of them and then select the needed ones.  But there are scenarios where different channels are stored separately (AMI).  We have to figure out at what level to do this.

Regarding the raw-PCM thing:  I think if there is any common/universal format it would probably be wav, not raw pcm, as raw pcm is too easy to get wrong (no error if wrong format).  I didn't really understand the AudioSource code well as your Python style is very modern... e.g. no __init__ function.

**Comment by pzelasko** [comment]
Regarding subests of channels - it's already supported, note the `test_get_audio_multichannel` - I'll document it better. I elaborated more in issue #4 

> Regarding the raw-PCM thing: I think if there is any common/universal format it would probably be wav, not raw pcm, as raw pcm is too easy to get wrong (no error if wrong format). 

That's just for the `command` type of input, where we could always place `sox` at the end of the pipe to convert practically anything to PCM, and it is very easy to load with numpy as it's just a cast of binary buffer to int16. But we can make it work with wav too I guess. 

>  I didn't really understand the AudioSource code well as your Python style is very modern... e.g. no init function.

Alright, let me elaborate on that. Python 3.7 introduced `dataclass`, based on [attrs](https://www.attrs.org/en/stable/) library. It basically reduces the amount of boilerplate code you need to write. You can specify the members similarly as in C++, e.g.:

```
@dataclass
class Foo:
  x: int
  y: List[str]
```

and it automatically creates default `__init__`, `__eq__`, etc. The `__init__` would look something like:

```
def __init__(self, x: int, y: List[str]):
  self.x = x
  self.y = y
  self.__post_init__()
```

It also provides a method `asdict` which can convert a `dataclass` into a nice dictionary, making serialization very easy (notice the code is quite terse for what it does). There's a `__post_init__` that's automatically called in the auto-generated constructor, it allows you to customize `__init__` without having to write the boilerplate.

Also, I find the `typing` module extremely useful for static code analysis and improving documentation. `List[int]` type means the variable will be a `list` of `int`, `Optional` means it can be `None`, `Union[int, str]` means it can be either an `int` or `str`.

**Comment by csukuangfj** [comment]
> Alright, let me elaborate on that. Python 3.7 introduced dataclass

The users of this library are **forced** to use Python 3.7. If some of them do not have
`sudo` permission, they will have difficulties upgrading their python version to 3.7

**Comment by danpovey** [comment]
Mm.  My feeling is the python3.7 thing may be OK... this is a rather forward-looking project, and my feeling is enough people have python3.7 (or could install it in user-space).
If it's a problem later we can always change the code, but for now I don't want to slow this project down by worrying too much about such thigns.

**Comment by pzelasko** [comment]
The users can also install Anaconda/Miniconda without sudo permissions and
use any python version they want.

czw., 7 maj 2020, 23:16 użytkownik Daniel Povey <notifications@github.com>
napisał:

**Comment by jtrmal** [comment]
plus python 3.7 was released mid 2018...
IMO it's ok
y.
