### ISSUE TITLE
Consistency between duration and number of frames

### ISSUE THREAD

**Issue by pzelasko** [pzelasko/lhotse#20]
Original comment from Dan:

It would probably make sense to have `duration` always be `n * frame_shift`, but understand that this is kind of approximate and actually it may use slightly more context than that?

I'd rather make it so that downstream, these cuts behave quite simply w.r.t. the relationship of duration and num-frames, and the user doesn't have to worry about the frame-length and how it may impact the num-frames.  That was a rabbit-hole in Kaldi itself.

_Originally posted by @danpovey in https://github.com/pzelasko/lhotse/pull/16_

**Comment by pzelasko** [comment]
Something I observed while addressing PR review in #19: while we're at it, the `Features` object should be [refactored as described here](https://github.com/pzelasko/lhotse/issues/8#issuecomment-641505583) so that we can expose the `num_frames` and `num_features` attribute in `Features` and `Cut` (`num_features` currently would require loading the feats from disk if the `FeatureExtractor` config is unknown).

**Comment by danpovey** [comment]
Wait, no, this stuff shouldn't need to be worked out from a config.  You should store the dimensions of the feature matrix along with the filename.  That is key information.

**Comment by danpovey** [comment]
BTW, lilcom can store arbitrary-dim matrices, you could just store the shape if you want.  
The frame shift could then be implicit from the number of frames and the duration.

**Comment by pzelasko** [comment]
> Wait, no, this stuff shouldn't need to be worked out from a config. You should store the dimensions of the feature matrix along with the filename. That is key information.

Yeah, that was my intention. Maybe I haven't expressed that so clearly.
