### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by pzelasko** [pzelasko/lhotse#29]
I'm thinking about a "read-the-docs" style doc page and adding some rationale, main features, and some examples in the README.md.

**Comment by pzelasko** [comment]
Any tips on which documentation tools are the best for the job and how to use them effectively will be appreciated.

**Comment by csukuangfj** [comment]
I guess sphinx (https://www.sphinx-doc.org/en/master/) is the right tool.

**Comment by danpovey** [comment]
Yeah, that seems to be the one everyone is using.  I wonder whether just a
few .md files might do the job too?  MIght be easier to read in text form.
But up to you...

**Comment by csukuangfj** [comment]
Sphinx supports both `*.md` files and `*.rst` files.

This extension (https://www.sphinx-doc.org/en/master/usage/markdown.html) is
helpful if you would like to write markdown files instead of reStructuredText files.

**Comment by danpovey** [comment]
Oh cool.
