### ISSUE TITLE
Sync the style of example bash scripts with Kaldi

### ISSUE THREAD

**Issue by jimbozhang** [pzelasko/lhotse#34]
The style of the librimix.sh is not quite similar as Kaldi's:
- librimix/s5/run.sh (kaldi)  vs. librimix/librimix.sh (lhotse)
- use stage blocks (kaldi)  vs. no stage (lhotse)
- some other differences

I'm writing the mini_librispeech recipe. I consider to use the kaldi-like style for the bash version. Not sure if it's a good idea. @pzelasko @danpovey 

If we choose to use the kaldi-like style, I'll update the the librimix recipe as well.

**Comment by danpovey** [comment]
I'd be OK adding `stage` steps to it, as that's  quite useful...
I don't see any other very significant differences.

We'll have to decide what to do about Kaldi tools, in case some are needed for the mini_librispeech recipe. I.e. whether to get them from Kaldi somehow or to commit them into lhotse.  I'm not sure myself.

**Comment by jimbozhang** [comment]
> We'll have to decide what to do about Kaldi tools, in case some are needed for the mini_librispeech recipe. I.e. whether to get them from Kaldi somehow or to commit them into lhotse. I'm not sure myself.

Take `download_and_untar.sh` as an example. Apparently we don't plan to rewrite it. But should we copy and add it into lhotse's repository or just fetch it from Kaldi's repository in lhose's script? I prefer the former, to avoid k2/lhotse depending on Kaldi too much.

**Comment by danpovey** [comment]
I'd be OK with copying it, since making lhotse free of dependencies like
that will make it more robust.  But we should find a way to avoid repeating
scripts that are not in local/.  E.g. we could perhaps make a directory
scripts/kaldi/ or something and put things like utils/ and steps/ in it,
mirroring Kaldi's structure, and then add soft links to the repo?  Of
course soft links won't work on Windows, but then most of Kaldi's scripts
won't either.

**Comment by mpariente** [comment]
If I can add my two cents. 
Bash scripts can be linked to lhotse directly using `entry_points` in the setup.py
In this way, they are binaries in the path so you can call them from anywhere as long as lhotse is installed.

**Comment by danpovey** [comment]
Mm.  From what I can see from reading online, that is for python scripts that you want to invoke as console scripts.
Our scripts are native bash,  etc.  (?)  I could be missing something.

**Comment by mpariente** [comment]
Ah sorry, it's not entry points, it's scripts. 
I set it up [here](https://github.com/mpariente/asteroid/pull/114/files), didn't merge but it works for bash script.

**Comment by pzelasko** [comment]
It seems there are not that many scripts in Kaldi that are directly re-usable in Lhotse, the major reason being that we ditched the original "data dir" structure. It is not that much work to re-implement the remaining ones in Python, making Lhotse a Python-centric library.

I think this is a great opportunity to make the library accessible to a wider community - I personally know some people are thrown off by bash. On the other hand, I know that having a CLI can be very convenient and many people are used to doing things this way. We can actually have the best of both worlds by implementing all/most of our scripts in Python and exposing them in CLI with a thin wrapper (I implemented most of `lhotse` modes like that already). I would strive for maintaining a high degree of feature parity between the Python library and the CLI.

As to `download_and_untar.sh`, this should be 5~10 lines of Python code, using the standard library:
https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve
https://docs.python.org/3/library/tarfile.html#examples

I'd see that as a Python function and a corresponding CLI wrapper mode such as `lhotse download`, which we could later extend to download different things like manifests, data, etc. either in a "smart" way (if its tar, unpack; if its zip, unzip, etc.) or controllable via parameters.

**Comment by danpovey** [comment]
If you have the bandwidth to convert to Python, that sounds great to me.
But I'd be cautious about putting everything as an "official", centralized
part of the package.
The "local/" concept in Kaldi was quite useful because many things are
dataset-specific and it doesn't always make sense to have a reusable tool.

**Comment by danpovey** [comment]
.. also, RE "lhotse download"... just think about whether it really belongs
with the rest of the package... I guess you could make a case either way.
But personally I feel like a simple existing Python function or even wget
or whatever might be fine.

**Comment by jimbozhang** [comment]
I agree with @pzelasko .Rewriting these utilities in Python would be pretty.

There is a `lhotse/recipes` path. I think we can put the `download_and_untar()` function in `lhotse/recipes/mini_librispeech.py`. This should be similar to Kaldi's `local`. @danpovey 

As for `lhose download`, I'm not sure if it's a necessary feature ...

**Comment by pzelasko** [comment]
Sounds good. If it turns out to be useful for other recipes, we can always
easily elevate it to the "global" utilities.

sob., 27 cze 2020, 11:50 użytkownik Junbo Zhang <notifications@github.com>
napisał:

**Comment by pzelasko** [comment]
I think this discussion is resolved - I might re-use some bits in the future when describing the code style.

**Comment by jimbozhang** [comment]
> I think this discussion is resolved - I might re-use some bits in the future when describing the code style.

I'll add the bash version recipe for mini_librispeech today.

**Comment by danpovey** [comment]
Fantastic!
