### ISSUE TITLE
Interfacing with externally extracted features

### ISSUE THREAD

**Issue by pzelasko** [pzelasko/lhotse#41]
Example use-case: somebody has their own feature extractor (e.g., a pre-trained network), and they want to use it with Lhotse. 

It is currently possible, but somewhat ugly - basically they have to ignore our `FeatureExtractor` and `FeatureSetBuilder` and construct the `FeatureSet` themselves. They will still need to pass a default `FeatureExtractor` to the `FeatureSet`.

I'm thinking of the following: 
- decouple `FeatureSetBuilder` from the `FeatureExtractor` so that somebody can supply their own feature extraction function
- make `FeatureExtractor` config optional in the `FeatureSet` (but added there by default in Lhotse) 

Update:

- Generic mechanism for adding custom feature extractors (feature extractor registry); should also specify for each feature type how to mix them, e.g. simple add, or exp-sum-log (or raise exceptions)
- Decoupling FeatureSetBuilder from FeatureExtractor
- Decoupling configuration for different feature extractor types
- Separate feature config from feature manifest (keep vital settings as part of individual feature documents)

**Comment by danpovey** [comment]
Sounds good.
It might eventually be helpful to include support for reading Kaldi
features, including compressed features.
I believe Karel Vesely has a python project that can do that.. it's for
python2 though, I think.

**Comment by popcornell** [comment]
There is also kaldiio which is used in ESPNet: https://github.com/nttcslab-sp/kaldiio.
