### ISSUE TITLE
Voice activity detection (VAD) dataset

### ISSUE THREAD

**Issue by pzelasko** [pzelasko/lhotse#60]

**Comment by pzelasko** [comment]
@jimbozhang would you like to take this one?

**Comment by jimbozhang** [comment]
Sure, I'd be glad to do this :smile_cat: 
If I didn't misunderstand it, this issue requires to add an example for VAD task.
Is there any recommended opensource data-set? I didn't find any on OpenSLR ...

**Comment by pzelasko** [comment]
Hmm, I think any ASR dataset that has speech and silence in it would be sufficient. Maybe AMI would be ok? I never worked with it, but these are meetings, so it should have continuous recordings. For VAD dataset, you'd discard the text in the supervisions and output a tensor of 0s for silence frames and 1s for speech frames. I think some setups in Kaldi also had 2 for noise frames, but IDK if that's necessary/useful? Maybe @danpovey or @jtrmal would know more.

AMI download: http://groups.inf.ed.ac.uk/ami/download/

**Comment by danpovey** [comment]
MM, my tendency would be to just have no supervision when training the
noise frames, i.e. to make it a don't-care.

**Comment by pzelasko** [comment]
But in that case it's also undefined what the system predicts during
inference in these frames, right? Maybe it's better to have only
speech/nonspeech?

sob., 1 sie 2020, 05:33 użytkownik Daniel Povey <notifications@github.com>
napisał:

**Comment by danpovey** [comment]
Well, yes, its undefined, but those frames could in practice contain either
speech or nonspeech, which is why you don't really want to train on them
as it would confuse the model.

**Comment by pzelasko** [comment]
Fair enough. I guess how you wish to treat the noisy/uncertain frames is dependent on a particular application.

**Comment by jimbozhang** [comment]
So we have decided to choose AMI. l trend to illustrate both ASR and VAD in the `ami` task.

**Comment by danpovey** [comment]
Great!
