### ISSUE TITLE
TTS recipe

### ISSUE THREAD

**Issue by jimbozhang** [pzelasko/lhotse#67]
I'm not sure if it useful to let lhotse support TTS training. If needed, I can make a TTS recipe using the [LJSpeech](https://keithito.com/LJ-Speech-Dataset/) corpus.
@danpovey @pzelasko

**Comment by danpovey** [comment]
That sounds like a great idea!  Yes, I intend for it to support all kinds
of speech-related tasks.

**Comment by pzelasko** [comment]
Yes, it will be most useful. Thanks!

**Comment by jimbozhang** [comment]
Just started working on this. A new recipe `ljspeech` will be added for end-to-end (e.g. Tacotron2) training. I'll make a PR next week.

**Comment by pzelasko** [comment]
Sounds great! A heads up - I made a couple of general changes in the meanwhile, e.g. the preferred manifest format is now JSON because it’s much faster to read/write.

**Comment by jimbozhang** [comment]
> Sounds great! A heads up - I made a couple of general changes in the meanwhile, e.g. the preferred manifest format is now JSON because it’s much faster to read/write.

I had a little worry: if the dataset is extremely huge, the JSON would be very large. To avoid out-of-memory, the manifest has to be splitted. I think splitting YAML is easier than JSON, because if you want to split a JSON, you have to load it into memory first.

**Comment by danpovey** [comment]
We had also discussed JSONL format (JSON, one element per line).
It will take quite a big dataset to hit that memory limit though.

**Comment by pzelasko** [comment]
Hmm, you're raising a good point. We can add JSONL quite easily - we're already supporting two formats anyway... 

I wonder if it makes sense to use a binary format for such super-large datasets. E.g. in https://github.com/huggingface/nlp/ they use Apache Arrow to traverse mmap-ed files, allowing them to iterate very large datasets with almost zero memory footprint (likely at the cost of storage size).

**Comment by danpovey** [comment]
Lets solve that only once it becomes a problem.
