### ISSUE TITLE
Suspicious supervisions in AMI

### ISSUE THREAD

**Issue by pzelasko** [pzelasko/lhotse#83]
There are 307 supervisions that have no text, and 5 of them have an extremely long duration (400 - 1600 seconds). See:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/15930688/93964388-736b7800-fd2d-11ea-9617-813bd23be78d.png">

@jimbozhang could you take a look at it?

**Comment by jimbozhang** [comment]
All the annotation are from http://groups.inf.ed.ac.uk/ami/AMICorpusAnnotations/ami_manual_annotations_v1.6.1_export.gzip

For the "No annotation found" warnings:
Indeed there is no annotation for these 5 audios in the gzip file.

For the no text supervisions:
`ami_manifests['dev']['supervisions']['IB4011.Headset-2.wav-12-0'].text == ''` , the corresponding line in the gzip file is:
`IB4011	C	MIO095 	2 	501.733	503.627	501.733	503.627	. 	713.34 	`, no text. There are voice in this audio segment, but no text in the annotation gzip file. I think this line is wrong.

For the long duration supervisions:
`ami_manifests['dev']['supervisions']['IB4002.Headset-2.wav-11-0'].duration > 1298` , the corresponding line in the gzip file is:
`IB4002	C	FIO093 	2 	108.059	109.184	108.059	109.184	. 	1406.34 	`. Also no text.
For the normal segments, the column-7 (109.184) should be equal of the column-9 (1406.34), but for the no-text line (I think those lines are just wrong annotations), the two column are not equal. The current lhotse takes 1406.34 as the end time, I'll fix it by taking 109.184 as the end time.
