### ISSUE TITLE
Full Librispeech recipe

### ISSUE THREAD

**Issue by jimbozhang** [pzelasko/lhotse#89]
Besides working on the PR #67 and #85, I'll add a full Librispeech recipe, which will support selecting the subsets, e.g. `train-clean-100`, `train-clean-360`, `dev-clean`, and so on.

The full Librspeech recipe will be ready before Oct. 15  @pzelasko @danpovey @songmeixu @qindazhu

**Comment by qindazhu** [comment]
Fantastic!! Many thanks! We may create example scripts with k2 based on your recipe.

**Comment by pzelasko** [comment]
It's merged, I extended the example notebook to include a DataLoader and make sure that it works without issues (PR #95, will merge after Dan's review)
