### ISSUE TITLE
Two issues kaldi style data formats have (that I'm hoping will be improved)

### ISSUE THREAD

**Issue by RuABraun** [pzelasko/lhotse#91]
Not sure if this is the right place, sorry if not. I have a vague memory of hearing in the recent kaldi community meetings one should make an issue for suggestions.

1. In kaldi the utterances are already split by speakers, there are no speaker changes inside an utterance. Depending on the use case, this is not at all realistic and ends up overestimating the impact of things like ivectors, as in reality speaker changes will cause degradations in performance (when using ivectors for example).
Because of that, I think one should add the option of doing decoding on a test set across speaker changes.

2. In kaldi decoding is never done on long utterances. This is of course because of the need to do alignment, but in practice decoding long audio files is a common usecase, and by segmenting it the LM loses context and one loses the ability (or rather it does not make sense to) to try out techniques that could take advantage of having hundreds of tokens to use as context. So I think there should be the capability of doing decoding on a test set of audio files where each audio files is at least several minutes long.

I guess by doing 2. one would get 1. for free as well.

Thank you for reading, Rudolf

**Comment by pzelasko** [comment]
Thanks Rudolf. This is also one of our main goals and both points are already enabled by Lhotse as long as the source corpus has full (uncut) recordings available (e.g. SWBD, AMI). It is the users choice if they want to cut them to speech segments,  equal duration windows, truncate in other way or retain full recordings (and most of these requires just a single function call).

**Comment by RuABraun** [comment]
Awesome :)
